[tool.ruff]
include = ["pyproject.toml", "test/**/*.py"]

[tool.ruff.lint]
ignore-init-module-imports = true
# allow duplicate imports
ignore=["F811"]
# https://docs.astral.sh/ruff/rules
select= [
    "UP007", "FA102", "I001",  # convert Union to | (pep-604)
    "F401", "E303",  # remove unused imports
    "PIE790",  # remove unnecessary pass statements
]

[tool.ruff.lint.per-file-ignores]
# do not touch imports here
"__init__.py" = ["F401"]
"conftest.py" = ["F401"]

[tool.pytest.ini_options]
asyncio_mode = "auto"