# coding: utf-8
"""Waylay Broker models.

This code was generated from the OpenAPI documentation of 'Waylay Broker'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.

"""

from __future__ import annotations

from enum import Enum


class Aggregate(str, Enum):
    """Aggregate."""

    MIN = "min"
    MAX = "max"
    MEAN = "mean"
    MEDIAN = "median"
    SUM = "sum"
    COUNT = "count"
    COUNT_MINUS_NON_MINUS_NUMERIC = "count-non-numeric"
    COUNT_MINUS_NUMERIC = "count-numeric"
    FIRST = "first"
    LAST = "last"
    STD = "std"
    DIFF = "diff"

    def __str__(self) -> str:
        return str(self.value)
