# coding: utf-8
"""Waylay Broker models.

This code was generated from the OpenAPI documentation of 'Waylay Broker'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.

"""

from __future__ import annotations

from enum import Enum


class Auto(str, Enum):
    """Auto."""

    AUTO = "auto"

    def __str__(self) -> str:
        return str(self.value)
