# coding: utf-8
"""Waylay Broker models.

This code was generated from the OpenAPI documentation of 'Waylay Broker'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.

"""

from __future__ import annotations

from typing import List

from pydantic import (
    ConfigDict,
    Field,
)
from typing_extensions import (
    Annotated,  # >=3.11
)

from waylay.sdk.api._models import BaseModel as WaylayBaseModel

from ..models.get_datapoints_for_metric_raw200_response_links import (
    GetDatapointsForMetricRaw200ResponseLinks,
)
from ..models.series_key_value_inner import SeriesKeyValueInner
from ..models.series_query_response import SeriesQueryResponse


class GetDatapointsForMetricRaw200Response(WaylayBaseModel):
    """GetDatapointsForMetricRaw200Response."""

    links: GetDatapointsForMetricRaw200ResponseLinks | None = Field(
        default=None, alias="_links"
    )
    query: SeriesQueryResponse
    series: List[
        Annotated[List[SeriesKeyValueInner | None], Field(min_length=2, max_length=2)]
    ] = Field(description="Array of timestamp-value tuples")

    model_config = ConfigDict(
        populate_by_name=True, protected_namespaces=(), extra="ignore"
    )
