# coding: utf-8
"""Waylay Broker models.

This code was generated from the OpenAPI documentation of 'Waylay Broker'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.

"""

from __future__ import annotations

from typing import List, Union

from typing_extensions import (
    Annotated,  # >=3.9
)

from ..models.scalar_data import ScalarData

Measurements = Union[Annotated[ScalarData, ""], Annotated["ObjectData", ""]]
ObjectData = Union[Annotated[object, ""], Annotated[List[Measurements], ""]]

"""Values in an _Event_ payload. Note that only _scalar_ data is stored in the timeseries, while Arrays and objects are only stored in the _Message Cache_.."""
