# coding: utf-8
"""Waylay Broker models.

This code was generated from the OpenAPI documentation of 'Waylay Broker'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.

"""

from __future__ import annotations

from datetime import datetime
from typing import (
    Union,
)

from typing_extensions import (
    Annotated,  # >=3.9
)

MessageQueryWindow = Union[
    Annotated[str, "Time interval with duration unit."], Annotated[datetime, ""]
]
"""A duration expression. Will be evaluated vs `from`, `until` or the query execution date to get the actual time range."""
