# coding: utf-8
"""Waylay Broker models.

This code was generated from the OpenAPI documentation of 'Waylay Broker'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.

"""

from __future__ import annotations

from datetime import datetime
from typing import Union

from typing_extensions import Annotated

MessageQueryUntil = Union[
    Annotated[
        int,
        "Timestamp expressed as milliseconds since 00:00:00 UTC on 1 January 1970,  not counting leap seconds.",
    ],
    Annotated[datetime, ""],
]
"""The upper bound of the time range to retrieve message from."""
