# coding: utf-8
"""Waylay Broker models.

This code was generated from the OpenAPI documentation of 'Waylay Broker'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.

"""

from __future__ import annotations

from typing import (
    Union,
)

from typing_extensions import (
    Annotated,  # >=3.9
)

from ..models.series_query_request import SeriesQueryRequest
from ..models.series_query_without_aggregates_request import (
    SeriesQueryWithoutAggregatesRequest,
)

MultipleSeriesQueryRequestInner = Union[
    Annotated[SeriesQueryRequest, ""],
    Annotated[SeriesQueryWithoutAggregatesRequest, ""],
]
"""MultipleSeriesQueryRequestInner."""
