# coding: utf-8
"""Waylay Broker models.

This code was generated from the OpenAPI documentation of 'Waylay Broker'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.

"""

from __future__ import annotations

from typing import (
    List,
    Union,
)

from typing_extensions import Annotated

from ..models.event import Event

PostSeriesForResourceRequest = Union[
    Annotated[Event, ""],
    Annotated[
        List[Event], "Array of measurement objects with optional event timestamp."
    ],
]
"""PostSeriesForResourceRequest."""
