# coding: utf-8
"""Waylay Broker models.

This code was generated from the OpenAPI documentation of 'Waylay Broker'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.

"""

from __future__ import annotations

from typing import (
    List,
    Union,
)

from typing_extensions import (
    Annotated,  # >=3.9
)

from ..models.resource_event import ResourceEvent

PostSeriesRequest = Union[
    Annotated[ResourceEvent, ""],
    Annotated[
        List[ResourceEvent],
        "Array of measurement objects with resource identifier and optional timestamp.",
    ],
]
"""PostSeriesRequest."""
