# coding: utf-8
"""Waylay Broker models.

This code was generated from the OpenAPI documentation of 'Waylay Broker'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.

"""

from __future__ import annotations

from pydantic import (
    ConfigDict,
    StrictStr,
)
from waylay.sdk.api._models import _BaseModel

from ..models.publish_event_response_content import PublishEventResponseContent


class PublishEventResponse(_BaseModel):
    """PublishEventResponse."""

    message: StrictStr | None = None
    content: PublishEventResponseContent | None = None

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
        extra="ignore",
    )
