# coding: utf-8
"""Waylay Broker models.

This code was generated from the OpenAPI documentation of 'Waylay Broker'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.

"""

from __future__ import annotations

from typing import (
    List,
    Union,
)

from typing_extensions import (
    Annotated,  # >=3.9
)

from ..models.empty import Empty
from ..models.timestamped_resource_event import TimestampedResourceEvent

PublishEventResponseContent = Union[
    Annotated[TimestampedResourceEvent, ""],
    Annotated[
        List[TimestampedResourceEvent],
        "Array of measurement objects with resource identifier and timestamp.",
    ],
    Annotated[Empty, ""],
]
"""PublishEventResponseContent."""
