# coding: utf-8
"""Waylay Broker models.

This code was generated from the OpenAPI documentation of 'Waylay Broker'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.

"""

from __future__ import annotations

from typing import (
    Union,
)

from typing_extensions import Annotated

TimeseriesFilterValueExactValue = Union[Annotated[float, ""], Annotated[str, ""]]
"""TimeseriesFilterValueExactValue."""
