# coding: utf-8
"""Waylay Broker models.

This code was generated from the OpenAPI documentation of 'Waylay Broker'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.

"""

from __future__ import annotations

from pydantic import (
    ConfigDict,
)
from waylay.sdk.api._models import _BaseModel

from ..models.timeseries_filter_operator_operator import (
    TimeseriesFilterOperatorOperator,
)


class TimeseriesFilterOperator(_BaseModel):
    """TimeseriesFilterOperator."""

    operator: TimeseriesFilterOperatorOperator

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
        extra="ignore",
    )
