# coding: utf-8
"""Waylay Broker: Query Parameters.

This code was generated from the OpenAPI documentation of 'Waylay Broker'

version: 2.18.0

Data is ingested into the platform by the Waylay Broker.

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""
