# coding: utf-8
"""Waylay Broker model tests.

This code was generated from the OpenAPI documentation of 'Waylay Broker'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.data.models.auto import Auto

    AutoAdapter = TypeAdapter(Auto)
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

auto_model_schema = json.loads(
    r"""{
  "title" : "auto",
  "type" : "string",
  "enum" : [ "auto" ]
}
""",
    object_hook=with_example_provider,
)
auto_model_schema.update({"definitions": MODEL_DEFINITIONS})

auto_faker = JSF(auto_model_schema, allow_none_optionals=1)


class AutoStub:
    """Auto unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return auto_faker.generate()

    @classmethod
    def create_instance(cls) -> "Auto":
        """Create Auto stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        return AutoAdapter.validate_python(cls.create_json())
