# coding: utf-8
"""Waylay Broker model tests.

This code was generated from the OpenAPI documentation of 'Waylay Broker'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.data.models.delete_series_from_parameter import (
        DeleteSeriesFromParameter,
    )

    DeleteSeriesFromParameterAdapter = TypeAdapter(DeleteSeriesFromParameter)
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

delete_series_from_parameter_model_schema = json.loads(
    r"""{
  "anyOf" : [ {
    "$ref" : "#/components/schemas/UnixEpochMillis"
  }, {
    "$ref" : "#/components/schemas/DurationWithUnit"
  } ]
}
""",
    object_hook=with_example_provider,
)
delete_series_from_parameter_model_schema.update({"definitions": MODEL_DEFINITIONS})

delete_series_from_parameter_faker = JSF(
    delete_series_from_parameter_model_schema, allow_none_optionals=1
)


class DeleteSeriesFromParameterStub:
    """DeleteSeriesFromParameter unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return delete_series_from_parameter_faker.generate(
            use_defaults=True, use_examples=True
        )

    @classmethod
    def create_instance(cls) -> "DeleteSeriesFromParameter":
        """Create DeleteSeriesFromParameter stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        json = cls.create_json()
        if json is None:
            # use backup example based on the pydantic model schema
            backup_faker = JSF(
                DeleteSeriesFromParameterAdapter.json_schema(), allow_none_optionals=1
            )
            json = backup_faker.generate(use_defaults=True, use_examples=True)
        return DeleteSeriesFromParameterAdapter.validate_python(
            json, context={"skip_validation": True}
        )
