# coding: utf-8
"""Waylay Broker model tests.

This code was generated from the OpenAPI documentation of 'Waylay Broker'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.data.models.empty import Empty

    EmptyAdapter = TypeAdapter(Empty)
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

empty_model_schema = json.loads(
    r"""{
  "title" : "Empty",
  "type" : "object",
  "description" : "Marks that multiple events where published",
  "enum" : [ { } ]
}
""",
    object_hook=with_example_provider,
)
empty_model_schema.update({"definitions": MODEL_DEFINITIONS})

empty_faker = JSF(empty_model_schema, allow_none_optionals=1)


class EmptyStub:
    """Empty unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return empty_faker.generate()

    @classmethod
    def create_instance(cls) -> "Empty":
        """Create Empty stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        return EmptyAdapter.validate_python(cls.create_json())
