# coding: utf-8
"""Waylay Broker model tests.

This code was generated from the OpenAPI documentation of 'Waylay Broker'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.data.models.get_datapoints_for_metric_raw200_response import (
        GetDatapointsForMetricRaw200Response,
    )

    GetDatapointsForMetricRaw200ResponseAdapter = TypeAdapter(
        GetDatapointsForMetricRaw200Response
    )
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

get_datapoints_for_metric_raw_200_response_model_schema = json.loads(
    r"""{
  "required" : [ "query", "series" ],
  "type" : "object",
  "properties" : {
    "_links" : {
      "$ref" : "#/components/schemas/getDatapointsForMetricRaw_200_response__links"
    },
    "query" : {
      "$ref" : "#/components/schemas/SeriesQueryResponse"
    },
    "series" : {
      "type" : "array",
      "description" : "Array of timestamp-value tuples",
      "items" : {
        "$ref" : "#/components/schemas/SeriesKeyValue"
      }
    }
  }
}
""",
    object_hook=with_example_provider,
)
get_datapoints_for_metric_raw_200_response_model_schema.update({
    "definitions": MODEL_DEFINITIONS
})

get_datapoints_for_metric_raw_200_response_faker = JSF(
    get_datapoints_for_metric_raw_200_response_model_schema, allow_none_optionals=1
)


class GetDatapointsForMetricRaw200ResponseStub:
    """GetDatapointsForMetricRaw200Response unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return get_datapoints_for_metric_raw_200_response_faker.generate()

    @classmethod
    def create_instance(cls) -> "GetDatapointsForMetricRaw200Response":
        """Create GetDatapointsForMetricRaw200Response stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        return GetDatapointsForMetricRaw200ResponseAdapter.validate_python(
            cls.create_json()
        )
