# coding: utf-8
"""Waylay Broker model tests.

This code was generated from the OpenAPI documentation of 'Waylay Broker'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.data.models.message_query_window import MessageQueryWindow

    MessageQueryWindowAdapter = TypeAdapter(MessageQueryWindow)
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

message_query_window_model_schema = json.loads(
    r"""{
  "title" : "MessageQuery_window",
  "description" : "A duration expression. Will be evaluated vs `from`, `until` or the query execution date to get the actual time range",
  "anyOf" : [ {
    "$ref" : "#/components/schemas/DurationWithUnit"
  }, {
    "$ref" : "#/components/schemas/SO8601Timestamp"
  } ]
}
""",
    object_hook=with_example_provider,
)
message_query_window_model_schema.update({"definitions": MODEL_DEFINITIONS})

message_query_window_faker = JSF(
    message_query_window_model_schema, allow_none_optionals=1
)


class MessageQueryWindowStub:
    """MessageQueryWindow unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return message_query_window_faker.generate(use_defaults=True, use_examples=True)

    @classmethod
    def create_instance(cls) -> "MessageQueryWindow":
        """Create MessageQueryWindow stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        json = cls.create_json()
        if json is None:
            # use backup example based on the pydantic model schema
            backup_faker = JSF(
                MessageQueryWindowAdapter.json_schema(), allow_none_optionals=1
            )
            json = backup_faker.generate(use_defaults=True, use_examples=True)
        return MessageQueryWindowAdapter.validate_python(
            json, context={"skip_validation": True}
        )
