# coding: utf-8
"""Waylay Broker model tests.

This code was generated from the OpenAPI documentation of 'Waylay Broker'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.data.models.multiple_series_query_request_inner import (
        MultipleSeriesQueryRequestInner,
    )

    MultipleSeriesQueryRequestInnerAdapter = TypeAdapter(
        MultipleSeriesQueryRequestInner
    )
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

multiple_series_query_request_inner_model_schema = json.loads(
    r"""{
  "title" : "MultipleSeriesQueryRequest_inner",
  "oneOf" : [ {
    "$ref" : "#/components/schemas/SeriesQueryRequest"
  }, {
    "$ref" : "#/components/schemas/SeriesQueryWithoutAggregatesRequest"
  } ]
}
""",
    object_hook=with_example_provider,
)
multiple_series_query_request_inner_model_schema.update({
    "definitions": MODEL_DEFINITIONS
})

multiple_series_query_request_inner_faker = JSF(
    multiple_series_query_request_inner_model_schema, allow_none_optionals=1
)


class MultipleSeriesQueryRequestInnerStub:
    """MultipleSeriesQueryRequestInner unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return multiple_series_query_request_inner_faker.generate(
            use_defaults=True, use_examples=True
        )

    @classmethod
    def create_instance(cls) -> "MultipleSeriesQueryRequestInner":
        """Create MultipleSeriesQueryRequestInner stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        json = cls.create_json()
        if json is None:
            # use backup example based on the pydantic model schema
            backup_faker = JSF(
                MultipleSeriesQueryRequestInnerAdapter.json_schema(),
                allow_none_optionals=1,
            )
            json = backup_faker.generate(use_defaults=True, use_examples=True)
        return MultipleSeriesQueryRequestInnerAdapter.validate_python(
            json, context={"skip_validation": True}
        )
