# coding: utf-8
"""Waylay Broker model tests.

This code was generated from the OpenAPI documentation of 'Waylay Broker'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.data.models.object_data import ObjectData

    ObjectDataAdapter = TypeAdapter(ObjectData)
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

object_data_model_schema = json.loads(
    r"""{
  "title" : "Object Data",
  "description" : "Event data stored only in the _Message Cache_.",
  "oneOf" : [ {
    "title" : "Object",
    "type" : "object"
  }, {
    "title" : "Array",
    "type" : "array",
    "items" : {
      "$ref" : "#/components/schemas/Measurements"
    }
  } ]
}
""",
    object_hook=with_example_provider,
)
object_data_model_schema.update({"definitions": MODEL_DEFINITIONS})

object_data_faker = JSF(object_data_model_schema, allow_none_optionals=1)


class ObjectDataStub:
    """ObjectData unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return object_data_faker.generate(use_defaults=True, use_examples=True)

    @classmethod
    def create_instance(cls) -> "ObjectData":
        """Create ObjectData stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        json = cls.create_json()
        if not json:
            # use backup example based on the pydantic model schema
            backup_faker = JSF(ObjectDataAdapter.json_schema(), allow_none_optionals=1)
            json = backup_faker.generate(use_defaults=True, use_examples=True)
        return ObjectDataAdapter.validate_python(
            json, context={"skip_validation": True}
        )
