# coding: utf-8
"""Waylay Broker model tests.

This code was generated from the OpenAPI documentation of 'Waylay Broker'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.data.models.post_series_request import PostSeriesRequest

    PostSeriesRequestAdapter = TypeAdapter(PostSeriesRequest)
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

post_series_request_model_schema = json.loads(
    r"""{
  "oneOf" : [ {
    "$ref" : "#/components/schemas/ResourceEvent"
  }, {
    "$ref" : "#/components/schemas/ResourceEvents"
  } ]
}
""",
    object_hook=with_example_provider,
)
post_series_request_model_schema.update({"definitions": MODEL_DEFINITIONS})

post_series_request_faker = JSF(
    post_series_request_model_schema, allow_none_optionals=1
)


class PostSeriesRequestStub:
    """PostSeriesRequest unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return post_series_request_faker.generate(use_defaults=True, use_examples=True)

    @classmethod
    def create_instance(cls) -> "PostSeriesRequest":
        """Create PostSeriesRequest stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        json = cls.create_json()
        if json is None:
            # use backup example based on the pydantic model schema
            backup_faker = JSF(
                PostSeriesRequestAdapter.json_schema(), allow_none_optionals=1
            )
            json = backup_faker.generate(use_defaults=True, use_examples=True)
        return PostSeriesRequestAdapter.validate_python(
            json, context={"skip_validation": True}
        )
