# coding: utf-8
"""Waylay Broker model tests.

This code was generated from the OpenAPI documentation of 'Waylay Broker'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.data.models.publish_event_response import PublishEventResponse

    PublishEventResponseAdapter = TypeAdapter(PublishEventResponse)
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

publish_event_response_model_schema = json.loads(
    r"""{
  "type" : "object",
  "properties" : {
    "message" : {
      "type" : "string"
    },
    "content" : {
      "$ref" : "#/components/schemas/PublishEventResponse_content"
    }
  }
}
""",
    object_hook=with_example_provider,
)
publish_event_response_model_schema.update({"definitions": MODEL_DEFINITIONS})

publish_event_response_faker = JSF(
    publish_event_response_model_schema, allow_none_optionals=1
)


class PublishEventResponseStub:
    """PublishEventResponse unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return publish_event_response_faker.generate()

    @classmethod
    def create_instance(cls) -> "PublishEventResponse":
        """Create PublishEventResponse stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        return PublishEventResponseAdapter.validate_python(cls.create_json())
