# coding: utf-8
"""Waylay Broker model tests.

This code was generated from the OpenAPI documentation of 'Waylay Broker'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.data.models.query_time_series_request import (
        QueryTimeSeriesRequest,
    )

    QueryTimeSeriesRequestAdapter = TypeAdapter(QueryTimeSeriesRequest)
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

query_time_series_request_model_schema = json.loads(
    r"""{
  "oneOf" : [ {
    "$ref" : "#/components/schemas/SeriesQueryRequest"
  }, {
    "$ref" : "#/components/schemas/MultipleSeriesQueryRequest"
  } ]
}
""",
    object_hook=with_example_provider,
)
query_time_series_request_model_schema.update({"definitions": MODEL_DEFINITIONS})

query_time_series_request_faker = JSF(
    query_time_series_request_model_schema, allow_none_optionals=1
)


class QueryTimeSeriesRequestStub:
    """QueryTimeSeriesRequest unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return query_time_series_request_faker.generate()

    @classmethod
    def create_instance(cls) -> "QueryTimeSeriesRequest":
        """Create QueryTimeSeriesRequest stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        return QueryTimeSeriesRequestAdapter.validate_python(cls.create_json())
