# coding: utf-8
"""Waylay Broker model tests.

This code was generated from the OpenAPI documentation of 'Waylay Broker'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.data.models.series_query_response import SeriesQueryResponse

    SeriesQueryResponseAdapter = TypeAdapter(SeriesQueryResponse)
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

series_query_response_model_schema = json.loads(
    r"""{
  "required" : [ "grouping", "metric", "resources" ],
  "type" : "object",
  "properties" : {
    "from" : {
      "$ref" : "#/components/schemas/UnixEpochMillis"
    },
    "until" : {
      "$ref" : "#/components/schemas/UnixEpochMillis"
    },
    "metric" : {
      "$ref" : "#/components/schemas/MetricId"
    },
    "aggregates" : {
      "type" : "array",
      "items" : {
        "$ref" : "#/components/schemas/Aggregate"
      }
    },
    "grouping" : {
      "$ref" : "#/components/schemas/Grouping"
    },
    "resources" : {
      "type" : "array",
      "items" : {
        "$ref" : "#/components/schemas/ResourceId"
      }
    },
    "filter" : {
      "$ref" : "#/components/schemas/TimeseriesFilter"
    },
    "limit" : {
      "minimum" : 1,
      "type" : "integer"
    }
  }
}
""",
    object_hook=with_example_provider,
)
series_query_response_model_schema.update({"definitions": MODEL_DEFINITIONS})

series_query_response_faker = JSF(
    series_query_response_model_schema, allow_none_optionals=1
)


class SeriesQueryResponseStub:
    """SeriesQueryResponse unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return series_query_response_faker.generate()

    @classmethod
    def create_instance(cls) -> "SeriesQueryResponse":
        """Create SeriesQueryResponse stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        return SeriesQueryResponseAdapter.validate_python(cls.create_json())
