# coding: utf-8
"""Waylay Broker model tests.

This code was generated from the OpenAPI documentation of 'Waylay Broker'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.data.models.timeseries_filter import TimeseriesFilter

    TimeseriesFilterAdapter = TypeAdapter(TimeseriesFilter)
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

timeseries_filter_model_schema = json.loads(
    r"""{
  "title" : "TimeseriesFilter",
  "description" : "Filter that will be applied to datapoints *before* aggregation is performed.",
  "allOf" : [ {
    "$ref" : "#/components/schemas/TimeseriesFilterOperator"
  }, {
    "$ref" : "#/components/schemas/TimeseriesFilterValue"
  } ]
}
""",
    object_hook=with_example_provider,
)
timeseries_filter_model_schema.update({"definitions": MODEL_DEFINITIONS})

timeseries_filter_faker = JSF(timeseries_filter_model_schema, allow_none_optionals=1)


class TimeseriesFilterStub:
    """TimeseriesFilter unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return timeseries_filter_faker.generate(use_defaults=True, use_examples=True)

    @classmethod
    def create_instance(cls) -> "TimeseriesFilter":
        """Create TimeseriesFilter stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        json = cls.create_json()
        if json is None:
            # use backup example based on the pydantic model schema
            backup_faker = JSF(
                TimeseriesFilterAdapter.json_schema(), allow_none_optionals=1
            )
            json = backup_faker.generate(use_defaults=True, use_examples=True)
        return TimeseriesFilterAdapter.validate_python(
            json, context={"skip_validation": True}
        )
