# coding: utf-8
"""Waylay Broker model tests.

This code was generated from the OpenAPI documentation of 'Waylay Broker'

Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import json

from jsf import JSF
from pydantic import TypeAdapter

from ..openapi import MODEL_DEFINITIONS, with_example_provider

try:
    from waylay.services.data.models.ttl_duration import TTLDuration

    TTLDurationAdapter = TypeAdapter(TTLDuration)
    MODELS_AVAILABLE = True
except ImportError as exc:
    MODELS_AVAILABLE = False

ttl_duration_model_schema = json.loads(
    r"""{
  "description" : "Specifies the duration of a TTL interval.",
  "oneOf" : [ {
    "$ref" : "#/components/schemas/DurationSeconds"
  }, {
    "$ref" : "#/components/schemas/DurationWithUnit"
  }, {
    "$ref" : "#/components/schemas/SO8601Duration"
  } ]
}
""",
    object_hook=with_example_provider,
)
ttl_duration_model_schema.update({"definitions": MODEL_DEFINITIONS})

ttl_duration_faker = JSF(ttl_duration_model_schema, allow_none_optionals=1)


class TTLDurationStub:
    """TTLDuration unit test stubs."""

    @classmethod
    def create_json(cls):
        """Create a dict stub instance."""
        return ttl_duration_faker.generate(use_defaults=True, use_examples=True)

    @classmethod
    def create_instance(cls) -> "TTLDuration":
        """Create TTLDuration stub instance."""
        if not MODELS_AVAILABLE:
            raise ImportError("Models must be installed to create class stubs")
        json = cls.create_json()
        if not json:
            # use backup example based on the pydantic model schema
            backup_faker = JSF(TTLDurationAdapter.json_schema(), allow_none_optionals=1)
            json = backup_faker.generate(use_defaults=True, use_examples=True)
        return TTLDurationAdapter.validate_python(
            json, context={"skip_validation": True}
        )
